name: SAST and DAST Parallel Execution

permissions:
  contents: write
  security-events: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  integration:
    name: Integration Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

  sast:
    name: SAST Analysis
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: 'codeql-results.sarif'
          upload: true

      - name: Upload SAST Results
        uses: actions/upload-artifact@v4
        with:
          name: sast-results-${{ github.sha }}
          path: codeql-results.sarif

  fuzzing:
    name: Fuzzing Analysis
    needs: sast
    runs-on: ubuntu-latest
    steps:
      - name: Pull OWASP ZAP Docker Image
        run: docker pull zaproxy/zap-stable

      - name: Prepare Results Directory
        run: mkdir -p ./results

      - name: Run OWASP ZAP Fuzzing
        run: |
          TARGET_URL="https://coride.site"
          docker run --user root --rm -v $(pwd):/zap/wrk:rw zaproxy/zap-stable zap-full-scan.py \
            -t $TARGET_URL \
            -r /zap/wrk/fuzz-report.html || true

      - name: List Results Directory
        run: ls -la .

      - name: Verify Results
        run: |
          test -f ./fuzz-report.html && echo "fuzz-report.html exists" || echo "fuzz-report.html is missing"

      - name: Upload Fuzzing Results
        uses: actions/upload-artifact@v4
        with:
          name: fuzzing-results-${{ github.sha }}
          path: ./fuzz-report.html

  dast:
    name: DAST Analysis
    needs: fuzzing
    runs-on: ubuntu-latest
    steps:
      - name: Pull OWASP ZAP Docker Image
        run: docker pull zaproxy/zap-stable

      - name: Run OWASP ZAP Baseline Scan
        run: |
          TARGET_URL="https://coride.site"
          docker run --user root --rm -v $(pwd):/zap/wrk:rw -w /zap zaproxy/zap-stable zap-baseline.py \
            -t $TARGET_URL \
            -J zap-output.json \
            -r zap-report.html \
            -d \
            -m 5 || true
      - name: Upload DAST Results
        uses: actions/upload-artifact@v4
        with:
          name: dast-results
          path: |
            zap-output.json
            zap-report.html